### ISSUE TITLE
File Open Dialog Key

### ISSUE THREAD

**Issue by ghost** [oomek/SuperPNG#1]
Currently, the file open dialog comes up every time when you hold down alt or shift.

I want it to come up when you hold down alt AND shift. So, needing both held down at the same time. That would fix the issue I'm having with batch processing. Thanks.

**Comment by oomek** [comment]
The change you suggested would also affect the regular file opening. I was trying to find the way to detect whether the plugin was launched from the batch or not, but no luck so far, this api is poorly doccumented.

**Comment by oomek** [comment]
I found a way to suppress the dialog in batches without affecting the shift or alt functionality when you normally open the file, but Suppress File Open Options Dialogs checkbox in the batch window must be UNCHECKED. Would that be acceptable?

**Comment by ghost** [comment]
Yeah, that would be acceptable. Thanks.

**Comment by ghost** [comment]
Please give me a link to the compiled plugin after it's done.

**Comment by oomek** [comment]
Can you test it please?
https://github.com/oomek/SuperPNG/releases

**Comment by ghost** [comment]
Just ran a batch with it, seems to work! Thank you!

**Comment by ghost** [comment]
By the way, I am curious why it can't work with the suppress file open menu option checked. Currently I don't have to do any batches on anything that would open one, but if I ever had to, and then save it as png, that could be annoying.

**Comment by oomek** [comment]
Because for some unknown for me reason
`descParams->playInfo` returns the following
When you open a file from menu it returns `plugInDialogSilent`
When you run from batch with Supress File Open Options ticked it returns `plugInDialogSilent`
When you run from batch with Supress File Open Options unticked it returns `plugInDialogDisplay`

So as you see I've had no other option. Maybe there is another way, but the documentation is very vague in that matter.

What would be annoying? Can you describe it in more detail?

**Comment by ghost** [comment]
If I had to do a batch operation where it opened a file type that had file open dialog I needed to be suppressed, and then save it as SuperPNG.

But in those edge cases I suppose I could just go back to making sure not to press alt/shift.

You could see if you can detect whether the Photoshop window is the active window. If Photoshop is running in the background, then you could conceivably just not have the shift/alt trigger work at all.

**Comment by oomek** [comment]
You just untick the box before running the batch, and the shift/alt suppression will work

**Comment by ghost** [comment]
Right, but what if I needed that box to suppress the file open dialogs of file types that aren't PNG? i.e. opening those filetypes and then saving them as png.

**Comment by oomek** [comment]
I'm going to test it, but The fileopen dialog pops up on opening, not saving the file.

**Comment by ghost** [comment]
Sorry, you're right. I had a brain fart. What I should've said is what if I wanted the batch process to include opening both those filetypes.

**Comment by oomek** [comment]
It depends if your other input file format requires the dialog suppression to be ticked.

**Comment by ghost** [comment]
Yeah. That's sort of what I always meant to say, I just got a wire crossed in my brain.

**Comment by oomek** [comment]
I've tried bmp, jpg, gif, tga and neither of those open a dialog when you press shift or alt and the suppress dialog is unchecked.

**Comment by oomek** [comment]
Btw. How do you construct your macros? I usualy have it that way:

![desktop screenshot 2018 11 30 - 09 40 49 16](https://user-images.githubusercontent.com/2974860/49281461-863ff900-f484-11e8-933c-eab615eec484.png)

**Comment by ghost** [comment]
Ah, good point. I forgot about that option.

Alright, sorry for the trouble there, I was just curious what I could do if I ever ran into that edge case, like with maybe obscure video game texture files or something.
